web:
  build: .
  command: 'web'
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
worker:
  build: .
  command: 'worker'
  working_dir: /app/user
  environment:
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
